services:
  - type: web
    name: booking-system-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    region: oregon
    plan: free
    branch: main
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: MONGODB_URI
        sync: false
      - key: ADMIN_TOKEN
        sync: false
